@url_base = http://localhost:5058/api/produto

### 1. Cadastrar um novo produto (Requer Admin)
# Você precisa primeiro fazer o login no arquivo usuario.http,
# copiar o token e colar aqui.
POST {{url_base}}/cadastrar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5AZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW5pc3RyYWRvciIsImV4cCI6MTc0OTcwNDk5NX0.cEPUn5uG1mFWtKXf-21N7chGJbEDGwPVFuqRMjwuxLs
Content-Type: application/json

{
    "nome" : "Bolacha Trakinas"
}


### 2. Listar todos os produtos (Requer Autenticação)
# Cole o token aqui também.
GET {{url_base}}/listar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5AZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW5pc3RyYWRvciIsImV4cCI6MTc0OTcwNDk5NX0.cEPUn5uG1mFWtKXf-21N7chGJbEDGwPVFuqRMjwuxLs

### 3. Buscar produto por ID (Requer Autenticação)
# Altere o '1' e cole o token.
GET {{url_base}}/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5AZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW5pc3RyYWRvciIsImV4cCI6MTc0OTcwNDk5NX0.cEPUn5uG1mFWtKXf-21N7chGJbEDGwPVFuqRMjwuxLs

### 4. Atualizar um produto (Requer Admin)
# Altere o '1' e cole o token.
PUT {{url_base}}/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5AZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW5pc3RyYWRvciIsImV4cCI6MTc0OTcwNDk5NX0.cEPUn5uG1mFWtKXf-21N7chGJbEDGwPVFuqRMjwuxLs

{
    "nome" : "Bolacha Trakinas de Chocolate"
}


### 5. Deletar um produto (Requer Admin)
# Altere o '1' e cole o token.
DELETE {{url_base}}/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5AZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW5pc3RyYWRvciIsImV4cCI6MTc0OTcwNDk5NX0.cEPUn5uG1mFWtKXf-21N7chGJbEDGwPVFuqRMjwuxLs